apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: practice-testp2-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/CHACHO617/DeberProcesosMinikube
    targetRevision: HEAD
    path: k8s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
